python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1004 --tag baseline 1004 Flip --augment Flip --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1005 --tag baseline 1005 Flip --augment Flip --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1006 --tag baseline 1006 Flip --augment Flip --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1007 --tag baseline 1007 Flip --augment Flip --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1008 --tag baseline 1008 Flip --augment Flip --num-workers 20 --project-name BMC_vision_classification

python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1004 --tag baseline 1004 Erase --augment Erase --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1005 --tag baseline 1005 Erase --augment Erase --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1006 --tag baseline 1006 Erase --augment Erase --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1007 --tag baseline 1007 Erase --augment Erase --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1008 --tag baseline 1008 Erase --augment Erase --num-workers 20 --project-name BMC_vision_classification

python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1004 --tag baseline 1004 SunFlare --augment SunFlare --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1005 --tag baseline 1005 SunFlare --augment SunFlare --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1006 --tag baseline 1006 SunFlare --augment SunFlare --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1007 --tag baseline 1007 SunFlare --augment SunFlare --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1008 --tag baseline 1008 SunFlare --augment SunFlare --num-workers 20 --project-name BMC_vision_classification

python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1004 --tag baseline 1004 BrightnessContrast --augment BrightnessContrast --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1005 --tag baseline 1005 BrightnessContrast --augment BrightnessContrast --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1006 --tag baseline 1006 BrightnessContrast --augment BrightnessContrast --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1007 --tag baseline 1007 BrightnessContrast --augment BrightnessContrast --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1008 --tag baseline 1008 BrightnessContrast --augment BrightnessContrast --num-workers 20 --project-name BMC_vision_classification

python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1004 --tag baseline 1004 RandomShadow --augment RandomShadow --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1005 --tag baseline 1005 RandomShadow --augment RandomShadow --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1006 --tag baseline 1006 RandomShadow --augment RandomShadow --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1007 --tag baseline 1007 RandomShadow --augment RandomShadow --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1008 --tag baseline 1008 RandomShadow --augment RandomShadow --num-workers 20 --project-name BMC_vision_classification

python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1004 --tag baseline 1004 GoodAugmentations --augment GoodAugmentations --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1005 --tag baseline 1005 GoodAugmentations --augment GoodAugmentations --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1006 --tag baseline 1006 GoodAugmentations --augment GoodAugmentations --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1007 --tag baseline 1007 GoodAugmentations --augment GoodAugmentations --num-workers 20 --project-name BMC_vision_classification
python baseline_train.py --batch-size 32 --epochs 40 --lr 0.0001 --model baseline --sublabel label --wandb True --seed 1008 --tag baseline 1008 GoodAugmentations --augment GoodAugmentations --num-workers 20 --project-name BMC_vision_classification
